name: "Build RPCh Crypto"
description: "Build RPCh Crypto"

runs:
  using: "composite"
  steps:
    - name: Cache toolchain
      uses: actions/cache@v3
      with:
        path: |
          ~/.rustup/toolchains
          ~/.rustup/update-hashes
          ~/.rustup/settings.toml
        key: ${{ runner.os }}-toolchain-${{ hashFiles('Cargo.lock') }}

    - name: Cache Cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

    - name: Install dependencies
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    # only install wasm-pack if we don't find it in cache
    # since it will cause an error otherwise
    - name: Install dependencies (wasm-pack)
      run: command -v wasm-pack || cargo install wasm-pack
      shell: bash

    - name: Build
      run: make build
      shell: bash
