name: Release

on:
  workflow_run:
    workflows:
      - Review
    types:
      - completed
    branches:
      - "release/**"

jobs:
  on-review-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "Review of the workflow failed, we are not publishing."
  on-review-success-publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Cache toolchain
        uses: actions/cache@v3
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
          key: ${{ runner.os }}-toolchain-${{ hashFiles('Cargo.lock') }}

      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Install dependencies
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # only install wasm-pack if we don't find it in cache
      # since it will cause an error otherwise
      - name: Install dependencies (wasm-pack)
        run: command -v wasm-pack || cargo install wasm-pack

      - name: Build
        run: make build

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - name: Publish package
        run: npm publish --access public ./pkg
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
